### ISSUE TITLE
Not setting Out of Stock

### ISSUE THREAD

**Issue by captainyoung** [etailer/Etailer_Backorders#2]
I am using Magento 1.9
I was having the issue, of "Out of Stock" not being set once the "Qty*" went below "Qty for Item's Status to Become Out of Stock" as a result of a customer buying a product.

The fix I did was in: Etailer_Backorders-master/app/code/community/Etailer/Backorders/Model/Item.php

You have to over ride the core function verifyStock by adding the following to the above file. This is because the original function ignores quantity settings if Backorders is set to "No Backorders"

`public function verifyStock($qty = null)
    {
        if ($qty === null) {
            $qty = $this->getQty();
        }
        if ($qty <= $this->getMinQty()) {
            return false;
        }
        return true;
    }
`

**Comment by rjocoleman** [comment]
Thanks for the report! 

I don't quite follow, could you please send a pull request?

**Comment by akkermanronald** [comment]
Hi both
After some testing in production we noticed the same issue. We will test the pull request mod.
Regards
Ronald

**Comment by rjocoleman** [comment]
closed in #3
