### ISSUE TITLE
"Backorderable" column appears in System->Cache Management screen

### ISSUE THREAD

**Issue by gebrial** [etailer/Etailer_Backorders#4]
A column with title "Backorderable" is appearing in the table in the System->Cache Management screen. I'm pretty sure it's from the addColumnsToGrid function from the class Etailer_Backorders_Model_Observer_Adminhtml. It appears to be due to the last condition in the if statement regarding Mage_Adminhtml_Block_Widget_Grid. I'm not sure where else that is used though.

**Comment by rjocoleman** [comment]
@gebrial Sorry I'm not seeing this.. what version of magento?

**Comment by rjocoleman** [comment]
sorry, I am.. I'm running an internal version of this to cope with some other use cases.. I'll take at look at the grid issue now.

**Comment by rjocoleman** [comment]
thanks @gebrial I've resolved this in https://github.com/etailer/Etailer_Backorders/commit/c13b76bb5f7bed9c8c465b6898451e208bc93194
